### ISSUE TITLE
avTransport events throw exception when connected via spotify direct

### ISSUE THREAD

**Issue by maru-sama** [SoCo/SoCo#453]
The latest stable sonos update finally supports spotify direct connect. While this works fine it apparently breaks avTransport events. If I play a track via spotify direct events throw following exception

Exception happened during processing of request from ('192.168.0.14', 35521)
<snip>
File "/Users/maru/source/python/virtual/kivy/lib/python2.7/site-packages/soco/data_structures.py", line 504, in from_element
    raise DIDLMetadataError("Missing restricted attribute")
DIDLMetadataError: Missing restricted attribute

For debugging purposes I put a debug print to see the returned element. Apparently I get THREE 

`<item xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" id="-1" parentID="-1"><res duration="0:04:10" protocolInfo="http-get:*:audio/x-spotify:*">x-sonos-spotify:spotify%3atrack%3a3zmOCkma2GQdMV4AZYLfZB?sid=9&amp;flags=0&amp;sn=9</res><upnp:albumArtURI>https://i.scdn.co/image/131f47a6be760db779ea6b0789235a224f19e9cb</upnp:albumArtURI><upnp:class>object.item.audioItem.musicTrack</upnp:class><dc:title>Fashionable People</dc:title><dc:creator>Joel Plaskett Emergency</dc:creator><r:albumArtist>Joel Plaskett Emergency</r:albumArtist><upnp:album>Ashtray Rock</upnp:album><r:tiid>591805489</r:tiid></item>
`

`<item xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" id="-1" parentID="-1"><res duration="0:03:45" protocolInfo="http-get:*:audio/x-spotify:*">x-sonos-spotify:spotify%3atrack%3a6kCQBXyvuCz8Vy4XPGIXQX?sid=9&amp;flags=0&amp;sn=9</res><upnp:albumArtURI>https://i.scdn.co/image/2a2a91a5ae23b8b7291c8a92eba5c7759f38798e</upnp:albumArtURI><upnp:class>object.item.audioItem.musicTrack</upnp:class><dc:title>Feeling You Got</dc:title><dc:creator>El Rego</dc:creator><r:albumArtist>El Rego</r:albumArtist><upnp:album>El Rego</upnp:album><r:tiid>2007133592</r:tiid></item>
`

`<item xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" id="-1" parentID="-1" restricted="true"><upnp:class>object.item.audioItem.audioBroadcast</upnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">https://sca-eu.ws.sonos.com/RINCON_000E58F9564801400:115/9/sn_9/v2.0/</desc></item>
`

The first one is the currently playing track, missing the restricted tag. The next item is the next entry in the queue. The last item is missing the title argument and apparently an audioBroadcast. 

Is this even in spec?

**Comment by nlagaros** [comment]
Can we ignore the restricted tag altogether?  Or if it is missing, just assume True?  It is one line of code to adjust in data_structures.py.

**Comment by Cereal2nd** [comment]
same happens for google play services

Exception happened during processing of request from ('192.168.1.2', 43951)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/lib/python2.7/dist-packages/soco/events.py", line 227, in do_NOTIFY
    variables = parse_event_xml(content)
  File "/usr/local/lib/python2.7/dist-packages/soco/events.py", line 130, in parse_event_xml
    value = from_didl_string(value)[0]
  File "/usr/local/lib/python2.7/dist-packages/soco/data_structures.py", line 99, in from_didl_string
    items.append(cls.from_element(elt))
  File "/usr/local/lib/python2.7/dist-packages/soco/data_structures.py", line 504, in from_element
    raise DIDLMetadataError("Missing restricted attribute")
DIDLMetadataError: Missing restricted attribute
----------------------------------------

**Comment by Cereal2nd** [comment]
looking at what i receive from google play

`<?xml version="1.0" encoding="UTF-8"?>
<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/">
   <item id="-1" parentID="-1">
      <res protocolInfo="http-get:*:audio/mpeg:*" duration="0:03:31">https://mclients.googleapis.com/music/mplay?mjck=Ta7kzjoymusrhv2gqhkzxb5rzwa&amp;pt=a&amp;dv=1&amp;slt=1483642918868&amp;sig=1XQrAIvWaEvHDrdJENg6X2tr0F0</res>
      <upnp:albumArtURI>http://lh3.googleusercontent.com/SRJu1KoeoLfexwJenStV8ym6iORiOrIzD3n-4GIZPXVKTCsLbjCAliO5Gvyb8VH6lDY5a-P4_fM</upnp:albumArtURI>
      <upnp:class>object.item.audioItem.musicTrack</upnp:class>
      <dc:title>Muhammad Ali (Radio Edit)</dc:title>
      <dc:creator>Faithless</dc:creator>
      <r:albumArtist>Faithless</r:albumArtist>
      <upnp:album>Forever Faithless - The Greatest Hits (C)</upnp:album>
      <r:tiid>6617792e-1927-4d7e-b522-a7a311fe7503</r:tiid>
   </item>
</DIDL-Lite>`

**Comment by Cereal2nd** [comment]
a fix is available in #466

**Comment by KennethNielsen** [comment]
#466 was superseded by #467 which should fix in the manner proposed here by @nlagaros. Feel free to test the PR branch.

**Comment by maru-sama** [comment]
Hello,

Sorry for the really long delay. But I can confirm that the pull request fixes the issue I am seeing with Spotify connect. That said there is still an error afterwards since apparently the title attribute is missing, but the initial reported problem

DIDLMetadataError: Missing restricted attribute

has been fixed.
